### ISSUE TITLE
can't open .roboFontProject through File/Open menu

### ISSUE THREAD

**Issue by casasin** [typemytype/projectRoboFontExtension#1]
It only works double-clicking the file from the finder: 
"The document 'myFont-Style.roboFontProject' could not be opened. The file isn't in the correct format. Unknown file format"
Is this intented or its expected behaviour?
thanks!

**Comment by typemytype** [comment]
yes, I know it silly, but you can change this in finder by setting the correct 'Open With' app

<img width="398" alt="screen shot 2017-01-11 at 14 59 38" src="https://cloud.githubusercontent.com/assets/1190358/21851278/a515dd8e-d80e-11e6-9406-f5547b9b1344.png">

Changing this programmatically seems not so easy
I should change this in the readme
